// <auto-generated />
using System;
using APIdeGerenciamentoDeTarefas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIdeGerenciamentoDomestico.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Comodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comodos");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Morador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moradores");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComodoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComodoId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.TarefaConcluida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ComodoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MoradorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComodoId");

                    b.HasIndex("MoradorId");

                    b.ToTable("TarefasConcluidas");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Tarefa", b =>
                {
                    b.HasOne("APIdeGerenciamentoDeTarefas.Models.Comodo", "Comodo")
                        .WithMany("Tarefas")
                        .HasForeignKey("ComodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comodo");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.TarefaConcluida", b =>
                {
                    b.HasOne("APIdeGerenciamentoDeTarefas.Models.Comodo", null)
                        .WithMany("TarefasConcluidas")
                        .HasForeignKey("ComodoId");

                    b.HasOne("APIdeGerenciamentoDeTarefas.Models.Morador", "morador")
                        .WithMany("TarefasConcluidas")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("morador");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Comodo", b =>
                {
                    b.Navigation("Tarefas");

                    b.Navigation("TarefasConcluidas");
                });

            modelBuilder.Entity("APIdeGerenciamentoDeTarefas.Models.Morador", b =>
                {
                    b.Navigation("TarefasConcluidas");
                });
#pragma warning restore 612, 618
        }
    }
}
